[project]
title = "Job Dataset Explorer"
version = "1.0.0"
port = 8501
slug = "job-dataset-explorer"
entrypoint = "hello.py"

[branding]
name = "Job Explorer App"
logo = "images/logo.png"
favicon = "images/favicon.ico"
primaryColor = "#0057D8"

[data.aug_test]
type = "csv"
path = "data/aug_test.csv"

[logging]
level = "INFO"
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
